package urn

type registeredNID string

// https://www.iana.org/assignments/urn-namespaces/urn-namespaces.xhtml
const (
	NID3GPP              registeredNID = "3gpp"
	NID3GPP2             registeredNID = "3gpp2"
	NIDAdID              registeredNID = "adid"
	NIDAlert             registeredNID = "alert"
	NIDBBF               registeredNID = "bbf"
	NIDBroadbandForumOrg registeredNID = "bbf"
	NIDCableLabs         registeredNID = "cablelabs"
	NIDCCSDS             registeredNID = "ccsds"
	NIDCGI               registeredNID = "cgi"
	NIDCLEI              registeredNID = "clei"
	NIDDGIWG             registeredNID = "dgiwg"
	NIDDSLForumOrg       registeredNID = "bbf"
	NIDDVB               registeredNID = "dvb"
	NIDEBU               registeredNID = "ebu"
	NIDEIDR              registeredNID = "eidr"
	NIDEPC               registeredNID = "epc"
	NIDEPCGlobal         registeredNID = "epc"
	NIDETSI              registeredNID = "etsi"
	NIDEurosystem        registeredNID = "eurosystem"
	NIDExample           registeredNID = "example"
	NIDFDC               registeredNID = "fdc"
	NIDFIPA              registeredNID = "fipa"
	NIDGEANT             registeredNID = "geant"
	NIDGlobus            registeredNID = "globus"
	NIDGSMA              registeredNID = "gsma"
	NIDHbbTV             registeredNID = "hbbtv"
	NIDIEEE              registeredNID = "ieee"
	NIDIETF              registeredNID = "ietf"
	NIDIPTC              registeredNID = "iptc"
	NIDISAN              registeredNID = "isan"
	NIDISBN              registeredNID = "isbn"
	NIDISO               registeredNID = "iso"
	NIDISSN              registeredNID = "issn"
	NIDITU               registeredNID = "itu"
	NIDIVIS              registeredNID = "ivis"
	NIDLiberty           registeredNID = "liberty"
	NIDMACE              registeredNID = "mace"
	NIDMEF               registeredNID = "mef"
	NIDMPEG              registeredNID = "mpeg"
	NIDMRN               registeredNID = "mrn"
	NIDNATO              registeredNID = "nato"
	NIDNBN               registeredNID = "nbn"
	NIDNENA              registeredNID = "nena"
	NIDNewsML            registeredNID = "newsml"
	NIDNFC               registeredNID = "nfc"
	NIDNZL               registeredNID = "nzl"
	NIDOASIS             registeredNID = "oasis"
	NIDOGC               registeredNID = "ogc"
	NIDOGF               registeredNID = "ogf"
	NIDOID               registeredNID = "oid"
	NIDOIPF              registeredNID = "oipf"
	NIDOMA               registeredNID = "oma"
	NIDONF               registeredNID = "onf"
	NIDPIN               registeredNID = "pin"
	NIDPublicID          registeredNID = "publicid"
	NIDS1000D            registeredNID = "S1000D"
)
